# Generated by Django 6.0.6 on 2026-07-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='actividad',
            field=models.CharField(choices=[('danza', 'Danza'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('funcional', 'Entrenamiento funcional')], default='danza', max_length=20),
        ),
    ]
