# Generated by Django 6.0.6 on 2026-07-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='proxima_cita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
